name             'cnos'
maintainer       'Lenovo'
maintainer_email 'cbhagavathip@lenovo.com'
license          'BSD-3-Clause'
description      'Implements an recipes for managing network resources on Lenovo switches'
version          '1.0.0'
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url       'https://github.com/lenovo/chef-cnos'
issues_url       'https://github.com/lenovo/chef-cnos/issues'
supports         'cnos'
chef_version     '>= 12.4'
